### [Mandatory] Add Book With Complete Data
POST http://localhost:9000/books
content-type: application/json

{   
    "name": "Buku A",
    "year": 2010,
    "author": "John Doe",
    "summary": "Lorem ipsum dolor sit amet",
    "publisher": "Dicoding Indonesia",
    "pageCount": 100,
    "readPage": 25,
    "reading": false
}

### [Mandatory] Add Book With Finished Reading
POST http://localhost:9000/books
content-type: application/json

{
    "name": "Buku A",
    "year": 2010,
    "author": "John Doe",
    "summary": "Lorem ipsum dolor sit amet",
    "publisher": "Dicoding Indonesia",
    "pageCount": 100,
    "readPage": 100,
    "reading": false

}

### [Mandatory] Add Book Without Name
POST http://localhost:9000/books
content-type: application/json

{
    "year": 2010,
    "author": "John Doe",
    "summary": "Lorem ipsum dolor sit amet",
    "publisher": "Dicoding Indonesia",
    "pageCount": 100,
    "readPage": 25,
    "reading": false
}

### [Mandatory] Add Book With Read Page Greater Than Page Count
POST http://localhost:9000/books
content-type: application/json

{
    "name": "Buku A",
    "year": 2010,
    "author": "John Doe",
    "summary": "Lorem ipsum dolor sit amet",
    "publisher": "Dicoding Indonesia",
    "pageCount": 80,
    "readPage": 90,
    "reading": false
}

### [Mandatory] Get All Books
GET http://localhost:9000/books

### [Mandatory] Get Detail Books With Correct Id
GET http://localhost:9000/books/XdgQgzeWppjNQgFx

### [Mandatory] Get Detail Finished Book
GET http://localhost:9000/books/XdgQgzeWppjNQgFx

### [Mandatory] Get Detail Books With Invalid Id
GET http://localhost:9000/books/xxxxx

### [Mandatory] Update Book With Complete Data
PUT http://localhost:9000/books/XdgQgzeWppjNQgFx
content-type: application/json

{
    "name": "Buku A Revisi",
    "year": 2011,
    "author": "Jane Doe",
    "summary": "Lorem Dolor sit Ametttt",
    "publisher": "Dicoding",
    "pageCount": 200,
    "readPage": 26,
    "reading": false
}

### [Mandatory] Update Book Without Name
PUT http://localhost:9000/books/XdgQgzeWppjNQgFx
content-type: application/json

{
    "year": 2011,
    "author": "Jane Doe",
    "summary": "Lorem Dolor sit Ametttt",
    "publisher": "Dicoding",
    "pageCount": 200,
    "readPage": 26,
    "reading": false
}

### [Mandatory] Update Book With Page Read More Than Page Count
PUT http://localhost:9000/books/XdgQgzeWppjNQgFx
content-type: application/json

{
    "name": "Buku A Revisi",
    "year": 2011,
    "author": "Jane Doe",
    "summary": "Lorem Dolor sit Ametttt",
    "publisher": "Dicoding",
    "pageCount": 80,
    "readPage": 90,
    "reading": false
}

### [Mandatory] Update Book with Invalid Id
PUT http://localhost:9000/books/xxxxx
content-type: application/json

{
    "name": "Buku A Revisi",
    "year": 2011,
    "author": "Jane Doe",
    "summary": "Lorem Dolor sit Ametttt",
    "publisher": "Dicoding",
    "pageCount": 200,
    "readPage": 26,
    "reading": false
}

### [Mandatory] Delete Book With Correct Id
DELETE http://localhost:9000/books/XdgQgzeWppjNQgFx

### [Mandatory] Delete Finished book
DELETE http://localhost:9000/books/d0GL5RtMCEUZJQKb

### [Mandatory] Delete Book with Invalid Id
DELETE http://localhost:9000/books/xxxxx

### [Optional] Add Reading and Finished Book
POST http://localhost:9000/books
content-type: application/json

{
    "name": "Buku A",
    "year": 2010,
    "author": "John Doe",
    "summary": "Lorem ipsum dolor sit amet",
    "publisher": "Dicoding Indonesia",
    "pageCount": 100,
    "readPage": 100,
    "reading": true
}

### [Optional] Add Reading and Unfinished Book with "Dicoding" Name
POST http://localhost:9000/books
content-type: application/json

{
    "name": "Kelas Dicoding",
    "year": 2010,
    "author": "John Doe",
    "summary": "Lorem ipsum dolor sit amet",
    "publisher": "Dicoding Indonesia",
    "pageCount": 100,
    "readPage": 99,
    "reading": true
}

### [Optional] Add Unreading Books and Unfinished Book "Dicoding" Name
POST http://localhost:9000/books
content-type: application/json

{
    "name": "dicoding Jobs",
    "year": 2010,
    "author": "John Doe",
    "summary": "Lorem ipsum dolor sit amet",
    "publisher": "Dicoding Indonesia",
    "pageCount": 100,
    "readPage": 0,
    "reading": false
}

### [Optional] Add Unreading Books and Unfinished Book
POST http://localhost:9000/books
content-type: application/json

{
    "name": "Buku A",
    "year": 2010,
    "author": "John Doe",
    "summary": "Lorem ipsum dolor sit amet",
    "publisher": "Dicoding Indonesia",
    "pageCount": 100,
    "readPage": 0,
    "reading": false
}

### [Optional] Get All Reading Books
GET http://localhost:9000/books?reading=1

### [Optional] Get All Unreading Books
GET http://localhost:9000/books?reading=0

### [Optional] Get All Finished Books
GET http://localhost:9000/books?finished=1

### [Optional] Get All Unfinished Books
GET http://localhost:9000/books?finished=0

### [Optional] Get All Books with "Dicoding" Name
GET http://localhost:9000/books?name=dicoding